# 步骤 2: 部署到 gh-pages 分支
  # 使用一个社区的 Action 来简化这个过程
  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v4
    with:
      # GitHub Actions 运行时的 GITHUB_TOKEN，用于推送
      github_token: ${{ secrets.GITHUB_TOKEN }}
      # 要部署的文件夹 (当前是根目录, 包含 .html 和 .js)
      publish_dir: .
      # 推送到的目标分支
      publish_branch: gh-pages
      # 排除 .github 目录和此文件本身
      exclude_assets: '.github,deploy.yml'
      # 提交信息
      commit_message: 'Deploy to GitHub Pages'
